version: "3.7"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    container_name: db
  rust:
    environment:
      USER: root
    volumes:
      - ./:/actix-app
    depends_on:
      - db
    container_name: rust
    build:
      context: .
      dockerfile: ./docker/rust/Dockerfile
