version: "3.7"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 5306:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    container_name: actix-db
  dev:
    image: rust:latest
    working_dir: /actix-app
    environment:
      USER: root
    volumes:
      - ./:/actix-app
    tty: true
    depends_on:
      - db
    container_name: actix-dev
    # build:
    #   context: .
    #   dockerfile: ./docker/rust/Dockerfile
